mcc -o YQ_VX -W main:YQ_VX -T link:exe -d /users/spelet1/YeastQuantX/YQ_VX/src...
    -N -p images -p signal -p stats -w enable:specified_file_mismatch -w enable:repeated_file -w enable:switch_ignored -w enable:missing_lib_sentinel -w enable:demo_license -R -nojvm -R -nodisplay -R -singleCompThread ...
    -v /users/spelet1/YeastQuantX/WrapFrameAnalysis.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/CalculatedObject.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/CombineData.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/CombineFrame.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/ExpandObject.m ...
    -a /users/spelet1/YeastQuantX/FrameAnalysis.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/Img2MovieRGB.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/LoadFrameMeas.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/LoadImage.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/MeasureObject.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/ObjectTransfer.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SecondaryObject.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SegmentNulcBF.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SegmentYeastFluo.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SegmentYeastFluoMedia.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SegmentYeastPhase.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SplitGroupHough.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/SubtractBackground.m ...
    -a /users/spelet1/YeastQuantX/CommonProcess/TrackObjectsSingle.m
